// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Badminton.Web.Models;

public partial class CheckIn
{
    public int CheckInId { get; set; }

    public int SubCourtId { get; set; }

    public int BookingId { get; set; }

    public DateTime CheckInTime { get; set; }

    public bool CheckInStatus { get; set; }

    public int UserId { get; set; }

    public virtual Booking Booking { get; set; }

    public virtual SubCourt SubCourt { get; set; }

    public virtual User User { get; set; }
}