// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Badminton.Web.Models;

public partial class Evaluate
{
    public int EvaluateId { get; set; }

    public int UserId { get; set; }

    public int CourtId { get; set; }

    public int Rating { get; set; }

    public string Comment { get; set; }

    public DateTime EvaluateDate { get; set; }

    public string CreatedBy { get; set; }

    public virtual Court Court { get; set; }

    public virtual User User { get; set; }
}