// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Badminton.Web.Models;

public partial class Promotion
{
    public int PromotionId { get; set; }

    public int CourtId { get; set; }

    public string PromotionName { get; set; }

    public string Description { get; set; }

    public decimal? DiscountPercentage { get; set; }

    public DateOnly StartDate { get; set; }

    public DateOnly EndDate { get; set; }

    public virtual ICollection<Booking> Bookings { get; set; } = new List<Booking>();

    public virtual Court Court { get; set; }

    public virtual ICollection<Payment> Payments { get; set; } = new List<Payment>();
}