// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Badminton.Web.Models;

public partial class Schedule
{
    public int ScheduleId { get; set; }

    public int UserId { get; set; }

    public int SubCourtId { get; set; }

    public DateOnly BookingDate { get; set; }

    public int TimeSlotID { get; set; }

    public decimal TotalHours { get; set; }

    public int BookingType { get; set; }

    public virtual ICollection<Booking> Bookings { get; set; } = new List<Booking>();

    public virtual SubCourt SubCourt { get; set; }

    public virtual User User { get; set; }
}