// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Badminton.Web.Models;

public partial class SubCourt
{
    public int SubCourtId { get; set; }

    public int CourtId { get; set; }

    public string Name { get; set; }

    public decimal PricePerHour { get; set; }

    public int TimeSlotId { get; set; }

    public virtual ICollection<Booking> Bookings { get; set; } = new List<Booking>();

    public virtual ICollection<CheckIn> CheckIns { get; set; } = new List<CheckIn>();

    public virtual Court Court { get; set; }

    public virtual ICollection<Schedule> Schedules { get; set; } = new List<Schedule>();

    public virtual TimeSlot TimeSlot { get; set; }
}