// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Badminton.Web.Models;

public partial class Verify
{
    public int VerifyId { get; set; }

    public int UserId { get; set; }

    public string Email { get; set; }

    public string Otp { get; set; }

    public DateTime ExpirationDateTime { get; set; }

    public DateTime VerifiedAt { get; set; }

    public virtual User User { get; set; }
}